services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: ["start-dev", "--import-realm", "--hostname=http://keycloak:8080"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9081:8080"
    volumes:
      - ./infra/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

  opa:
    image: openpolicyagent/opa:0.68.0
    command: ["run", "--server", "--addr=0.0.0.0:8181", "/policies"]
    ports:
      - "8181:8181"
    volumes:
      - ./infra/opa/policies:/policies:ro

  banking-api-service:
    build:
      context: .
      dockerfile: services/banking-api-service/Dockerfile
    environment:
      BANKING_API_JWK_SET_URI: http://keycloak:8080/realms/banking-poc/protocol/openid-connect/certs
      BANKING_API_ISSUER_URI: http://keycloak:8080/realms/banking-poc
      BANKING_API_AUDIENCE: mobile-banking-app
    depends_on:
      - keycloak

  identity-bootstrap-service:
    build:
      context: .
      dockerfile: services/identity-bootstrap-service/Dockerfile
    environment:
      KEYCLOAK_ADMIN_SERVER_URL: http://keycloak:8080
      KEYCLOAK_ADMIN_REALM: banking-poc
      KEYCLOAK_ADMIN_ADMIN_REALM: master
      KEYCLOAK_ADMIN_CLIENT_ID: admin-cli
      KEYCLOAK_ADMIN_USERNAME: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DEMO_BOOTSTRAP_SECRET: demo-bootstrap-secret
    depends_on:
      - keycloak

  kong:
    image: kong:3.7
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PLUGINS: bundled,opa-authz
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      banking-api-service:
        condition: service_started
        restart: true
      opa:
        condition: service_started
    volumes:
      - ./infra/kong/kong.yml:/etc/kong/kong.yml:ro
      - ./infra/kong/plugins/opa-authz:/usr/local/share/lua/5.1/kong/plugins/opa-authz:ro
